name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      skip-e2e:
        type: boolean
        description: 'Skip e2e test'
        required: false
        default: false

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  e2e:
    if: ${{ !inputs.skip-e2e }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Install Playwright
        run: npx playwright install

      - name: Execute Playwright
        run: npx playwright test
        env:
          AXE_DEVHUB_API_KEY: ${{ secrets.AXE_DEVHUB_API_KEY }}
  axe-dev-hub:
    if: ${{ !inputs.skip-e2e }}
    runs-on: ubuntu-latest
    needs: [e2e]
    steps:
      - uses: actions/checkout@v4
      - uses: dequelabs/axe-devhub-action@v1
        with:
          api_key: ${{ secrets.AXE_DEVHUB_API_KEY }}        
  build-and-deploy:
    runs-on: ubuntu-latest
    needs: [axe-dev-hub]
    if: ${{needs.axe-dev-hub.result == 'success' || !inputs.skip-e2e}}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build
        continue-on-error: true

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          branch: gh-pages
